### ISSUE TITLE
Migrate CircleCI to a 2.0 configuration

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/linter-coffeelint#102]
CircleCI will be [removing support for 1.0](https://circleci.com/blog/sunsetting-1-0/) configurations as of 2018-08-31. This is one of the repositories within this organization that is currently still configured to use a 1.0 configuration and needs to be migrated to the 2.0 format.

An automated translation can be found [here](https://circleci.com/api/v1.1/project/github/AtomLinter/linter-coffeelint/config-translation), however it is likely that a better method would be to follow the Workflow based example from [AtomLinter/atom-minimap-linter](https://github.com/AtomLinter/atom-minimap-linter/blob/master/.circleci/config.yml).

**Comment by UziTech** [comment]
I've never used Circle CI so I might need some help with this. Any idea why it is failing? And, maybe more importantly, why it isn't showing an error?

https://circleci.com/gh/UziTech/linter-coffeelint/4

**Comment by Arcanemagus** [comment]
Atom currently has a regression where the Electron error messages (before Atom initializes) aren't shown, I'll run this locally to check with `--enable-electron-logging`.

And no worries, I'll get to this soon, I just filed all the issues so I had something to track all the repos that need upgrading 😉.

**Comment by Arcanemagus** [comment]
Looks like the `${APM_SCRIPT_PATH} install` step was missed in the config.

```ShellSession
atom@e52ced553444:~/linter-coffeelint$ ${ATOM_SCRIPT_PATH} --enable-electron-logging --test spec
[91:0228/050454.570071:ERROR:bus.cc(427)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[91:0228/050454.589901:WARNING:audio_manager.cc(317)] Multiple instances of AudioManager detected
[91:0228/050454.590037:WARNING:audio_manager.cc(278)] Multiple instances of AudioManager detected
[91:0228/050458.029180:INFO:CONSOLE(109)] "Error: Cannot find module 'jasmine-fix'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:350:52)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:47:27)
    at Object.<anonymous> (/home/atom/linter-coffeelint/spec/linter-coffeelint-spec.js:3:28)
    at Object.<anonymous> (/home/atom/linter-coffeelint/spec/linter-coffeelint-spec.js:130:4)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:234:23)
    at Module.load (/usr/share/atom/resources/app.asar/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:47:27)
    at requireSpecs (/usr/share/atom/resources/app.asar/spec/jasmine-test-runner.js:98:9)
    at module.exports (/usr/share/atom/resources/app.asar/spec/jasmine-test-runner.js:51:7)
    at module.exports (/usr/share/atom/resources/app.asar/src/initialize-test-window.js:93:17)
    at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:106:12)
    at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:67:9)", source: /usr/share/atom/resources/app.asar/src/initialize-test-window.js (109)
```

**Comment by Arcanemagus** [comment]
FYI, for your own info if you have Docker installed on your machine you can test everything locally in an _almost_ identical environment to the CI run, that's the beauty of running this from a common image:

```ShellSession
abneyl@foo:linter-coffeelint$ docker run --rm -it arcanemagus/atom-docker-ci:stable bash
atom@2e12879e48b9:~$ git clone --quiet https://github.com/AtomLinter/linter-coffeelint.git
atom@2e12879e48b9:~$ cd linter-coffeelint/
atom@2e12879e48b9:~/linter-coffeelint$ ${APM_SCRIPT_PATH} install
Installing modules ✓
atom@2e12879e48b9:~/linter-coffeelint$ ${ATOM_SCRIPT_PATH} --test spec
..........

Finished in 3.852 seconds
10 tests, 34 assertions, 0 failures, 0 skipped

atom@2e12879e48b9:~/linter-coffeelint$
```

Additionally CircleCI has the absolutely _amazing_ feature of being able to run builds with SSH enabled, allowing you to log into the _exact_ environment your CI build is running in if local testing is unable to show the issue.

_Note: Although you need to manually start the `Xvfb` in the CI scripts, I managed to make it automatically start when running it yourself, which is why you don't see that in the steps there._

**Comment by UziTech** [comment]
I updated a few things including the circle ci configuration. I added [USER](https://github.com/AtomLinter/linter-coffeelint/blob/2a9ae66329c568119d98e23d9f9628afa29700b1/circle.yml#L7) to the environment variables to pass the beta channel for now.

I'll leave this issue open so you can keep track of the Circle CI v2 rollout across AtomLinter
