### ISSUE TITLE
Uncaught TypeError: Cannot read property 'coffeelintConfig' of null

### ISSUE THREAD

**Issue by sadovnychyi** [AtomLinter/linter-coffeelint#27]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter-coffeelint](https://github.com/AtomLinter/linter-coffeelint) package, v0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'coffeelintConfig' of null

```
At /Users/dmitry/.atom/packages/linter-coffeelint/node_modules/coffeelint/lib/configfinder.js:37

TypeError: Cannot read property 'coffeelintConfig' of null
  at loadNpmConfig (/Users/dmitry/.atom/packages/linter-coffeelint/node_modules/coffeelint/lib/configfinder.js:37:26)
  at Object.exports.getConfig (/Users/dmitry/.atom/packages/linter-coffeelint/node_modules/coffeelint/lib/configfinder.js:62:17)
  at LinterCoffeelint.lintFile (/Users/dmitry/.atom/packages/linter-coffeelint/lib/linter-coffeelint.coffee:46:27)
  at /Users/dmitry/.atom/packages/linter/lib/linter-view.coffee:158:18
  at Array.forEach (native)
  at /Users/dmitry/.atom/packages/linter/lib/linter-view.coffee:157:18
  at FSReqWrap.oncomplete (fs.js:100:15)

```

### Commands

```
  3x -1:13.1 core:move-down (atom-text-editor.editor.is-focused)
     -1:10.9 editor:delete-to-beginning-of-line (atom-text-editor.editor.is-focused)
     -1:10.5 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:07.9 core:paste (atom-text-editor.editor.is-focused)
     -0:54.1 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:53.8 core:backspace (atom-text-editor.editor.is-focused)
     -0:52.0 core:copy (atom-text-editor.editor.is-focused)
  7x -0:49.3 core:undo (atom-text-editor.editor.is-focused)
 14x -0:43.5 core:redo (atom-text-editor.editor.is-focused)
     -0:38.6 core:paste (atom-text-editor.editor.is-focused)
  7x -0:38.2 core:backspace (atom-text-editor.editor.is-focused)
     -0:36.8 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:36.8 core:cancel (atom-text-editor.editor.is-focused)
  2x -0:36.0 core:save (atom-text-editor.editor.is-focused)
     -0:33.8 core:close (atom-text-editor.editor.is-focused)
  2x -0:06.3 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      ".pyc"
    ],
    "projectHome": "~/code",
    "disabledPackages": [
      "atom-ctags"
    ],
    "followSymlinks": true,
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  },
  "linter-coffeelint": {}
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
atom-beautify, v0.23.1
atom-jinja2, v0.5.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.7.0
color-picker, v1.5.0
editorconfig, v0.3.3
file-icons, v1.5.2
highlight-line, v0.10.1
highlight-selected, v0.9.1
language-docker, v1.1.3
linter, v0.12.0
linter-coffeelint, v0.2.0
linter-flake8, v1.3.0
linter-scss-lint, v0.0.14
monokai, v0.13.0
open-last-project, v0.3.5
project-manager, v1.15.5
regex-railroad-diagram, v0.7.1
revert-buffer, v0.5.0
welcome, v0.26.0

# Dev
No dev packages
```

**Comment by jazzpi** [comment]
I just encountered this issue randomly too - for me, it appeared after switching tabs. It doesn't appear everytime I switch tabs though.

**Comment by AsaAyers** [comment]
Based on the line number, it seems you have a `package.json` that can't be parsed. Maybe you forgot a comma or have an extra comma?

**Comment by sadovnychyi** [comment]
Looks like yes, I had a package.json with wrong syntaxis, but its in my
project, why something from my project should be able to broke the whole
editor?

**Comment by jazzpi** [comment]
I think I had a broken `package.json` too, but that *really* shouldn't throw an error every time I hit a key anywhere in the editor.

**Comment by AsaAyers** [comment]
You're using a linter. By it's nature it runs every time you type something. So yes, if something happens to cause it to crash reliably, it will crash every time you type something.

It's looking for your coffeelint configuration. One place you can put it is in your package.json. I will update CoffeeLint so it doesn't throw when it can't parse a `package.json`.
