### ISSUE TITLE
Does not search in node_modules to find the appropriate modules

### ISSUE THREAD

**Issue by n0m0r3pa1n** [AtomLinter/linter-coffeelint#64]
I added some additional modules to the coffeelint.json like:
"no_trailing_commas": {
    "module": "coffeelint-no-trailing-commas",
    "level": "error"
  },

I have the plugin installed and visible in the node_modules folder of the project. 

When I open one of the files in my project there is a crash in the console. The linter-coffee plugin does not search in the node_modules folder, I don't know if it expects me to install the plugin globally.

This is the error I get:

Cannot find module 'coffeelint-no-trailing-commas' from '/home/joro/WorkSpace/getti/js/clover-be/src/routes'
/home/joro/.atom/packages/linter-coffeelint/lib/core.coffee:91 Error: Cannot find module 'coffeelint-no-trailing-commas' from '/home/joro/WorkSpace/getti/js/clover-be/src/routes'
  at module.exports (/home/joro/WorkSpace/getti/js/clover-be/node_modules/resolve/lib/sync.js:32:11)
  at expandModuleNames (/home/joro/WorkSpace/getti/js/clover-be/node_modules/coffeelint/lib/configfinder.js:84:33)
  at Object.exports.getConfig (/home/joro/WorkSpace/getti/js/clover-be/node_modules/coffeelint/lib/configfinder.js:137:16)
  at Object.module.exports.lint (/home/joro/.atom/packages/linter-coffeelint/lib/core.coffee:79:29)
  at _Class.module.exports._Class.lint (/home/joro/.atom/packages/linter-coffeelint/lib/plus-linter.coffee:43:19)
  at _Class.lint (/home/joro/.atom/packages/linter-coffeelint/lib/plus-linter.coffee:1:1)
  at promises.push.Promise.then._this.emitter.emit.linter (/home/joro/.atom/packages/linter/lib/linter-registry.js:95:28)
  at /home/joro/.atom/packages/linter/lib/linter-registry.js:94:25
  at Set.forEach (native)
  at LinterRegistry.lint (/home/joro/.atom/packages/linter/lib/linter-registry.js:92:20)
  at /home/joro/.atom/packages/linter/lib/linter.coffee:98:16
  at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
  at /home/joro/.atom/packages/linter/lib/editor-linter.js:100:23
  at /home/joro/.atom/packages/linter/lib/helpers.coffee:23:18

**Comment by n0m0r3pa1n** [comment]
I think the problem is in the core.coffee file and it is connected with the filePath variable which is passed to the lint method. I think the configFinder.getConfig is throwing an exception. When I manually place the path it does not throw anything but I still can not make it work with the plugins. It works when I call : coffeelint -f coffeelint.json  ./src/

**Comment by AsaAyers** [comment]
Nothing is expecting you to install globally. IMO `npm install -g` is a bad idea and should only be allowed for packages that expose a shell command.

Do you also have coffeelint installed as a dependency of your project?

**Comment by n0m0r3pa1n** [comment]
Yes, it is a local dependency. This is part of the package.json:

"devDependencies": {
    "assert": "^1.3.0",
    "chai": "^3.5.0",
    "co-mocha": "^1.1.2",
    "coffeelint-camel-case-vars": "0.0.4",
    "coffeelint-forbidden-keywords": "~0.1.1",
    "coffeelint-function-call-whitespace": "~0.1.3",
    "coffeelint-limit-newlines": "~0.0.2",
    "coffeelint-no-class-fat-arrows": "^0.1.0",
    "coffeelint-no-implicit-returns": "0.0.5",
    "coffeelint-no-trailing-commas": "~1.0.3",
    "coffeelint-prefer-double-quotes": "~0.1.0",
    "coffeelint-variable-scope": "~0.0.3",
    "inject-then": "^2.0.5",
    "mocha": "^2.4.5",
    "mocha-mongoose": "^1.1.1",
    "sinon": "^1.17.3"
  }

I debugged the configFinder. The exposeModules function in the config file throws an exception.

**Comment by AsaAyers** [comment]
https://github.com/jasonku/coffeelint-no-trailing-commas/blob/master/package.json#L5

That package is broken. Their `package.json` says the entry point is `index.js`, but that file doesn't exist. They should be publishing compiled JavaScript to NPM and `main` has to point to that file.

**Comment by n0m0r3pa1n** [comment]
Wow, thanks! It took me several hours of wondering and debugging. That exception stack trace is so bad...
